variables:
- group: pub-dev1

trigger:
- develop

pool: $(pool)

steps:

- task: DotNetCoreCLI@2
  displayName: "dotnet pack project"
  inputs:
    command: 'pack'
    projects: $(project)
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'version'

- task: DotNetCoreCLI@2
  displayName: "dotnet push $(feed)"
  inputs:
    command: 'push'
    nugetFeedType: 'internal'
    feedPublish: $(feed)